$kind: http-request
description: |-
  Create a new role

  Idempotency: Via UNIQUE(code)
url: "{{base_url}}/v1/roles"
method: POST
headers:
  Content-Type: application/json
body:
  type: text
  content: |-
    {
      "code": "admin",
      "name": "Administrator",
      "description": "Full system access",
      "status": "active"
    }
scripts:
  - type: afterResponse
    code: |-
      var jsonData = pm.response.json();
      pm.environment.set("role_id", jsonData.role_id);
    language: text/javascript
order: 1000
